### ISSUE TITLE
How to explain HVSR results obtained using iris-hvsr-tool and local data processing program like geopsy?

### ISSUE THREAD

**Issue by chenyqmy** [iris-edu/HVSR#1]
Hello,
I find that iris-hvsr-tool is a very fast way to obtain hvsr results of the seismic data avaliable from IRIS database. The differences in the hvsr results calculated by iris-hvsr-tool and geopsy for the same data were compared, the difference between them is quite big for predominant frequency.
The example is "computeHVSR.py net=YT sta=DNTW loc= chan=HHZ,HHN,HHE start=2017-01-02 end=2017-01-03 plot=1 plotpsd=0 plotpdf=0 ymax=5 xtype=frequency n=1 removeoutliers=0 method=4"
and i downloaded the data to obtain hvsr using geopsy. i got two different peak freqency results.The results are 0.519Hz and 0.412Hz respectively.
Can you help me to explain it?
I noticed MUSTANG algorithm can smooth peaks, will it affect frequency values?
Thank you for your help.

**Comment by manoch-iris** [comment]
Hello,

As you suggested, the observed shift in frequency is due to smoothing that MUSTANG applies. We have pointed to this in our article:

_Manochehr Bahavar, Zack J. Spica, Francisco J. Sánchez‐Sesma, Chad Trabant, Arash Zandieh, Gabriel Toro; Horizontal‐to‐Vertical Spectral Ratio (HVSR) IRIS Station Toolbox. Seismological Research Letters 2020;; 91 (6): 3539–3549. doi: https://doi.org/10.1785/0220200047_

and in the description of the method https://github.com/iris-edu/HVSR (see the note at the end of this reply). You can read more about MUSTANG smoothing  here: http://service.iris.edu/mustang/noise-psd/docs/1/help/. 

As mentioned in the above link,  there is a tradeoff between enhancing frequency resolution and reducing variance of the PSDs. By reducing the variance of PSD features requiring detailed frequency resolution will appear smeared in these PSDs that translates to a frequency shift of HVSR peaks.

Please also see the following article for a more detailed discussion:

_Robert E. Anthony, Adam T. Ringler, David C. Wilson, Manochehr Bahavar, Keith D. Koper; **How Processing Methodologies Can Distort and Bias Power Spectral Density Estimates of Seismic Background Noise**. Seismological Research Letters 2020;; 91 (3): 1694–1706. doi: https://doi.org/10.1785/0220190212_

As you have discovered, The HVSR tool is very fast and allows you to scan days/months of HVSR quickly. Once you have isolated the interval you want to study, using a different frequency analysis tool with less smoothing is required. 

Best,
--manoch
--------------
"NOTE: The MUSTANG noise-psd web service Power Spectral Density estimate for seismic channels are computed using the algorithm outlined here: (http://service.iris.edu/mustang/noise-psd/docs/1/help/) This algorithm involves averaging and normalization that may result in smoothing of some of the peaks that may otherwise be observed by direct computation of FFT and DFA.

**Comment by chenyqmy** [comment]
Thank you for answers and suggestions.
